alignment
front-end-by-rimantas/19-grupe-portfolio-personal pull request #72
Opened 2020-12-14 10:54 UTC by Alekslov

2020-12-14 11:24 UTC, vaidas33 submitted a review, later dismissed

2020-12-14 19:34 UTC, anavisnia commented on css/components/plan.css
>      padding-top: 40px;
Per daug paddingo is virsaus.

2020-12-14 19:34 UTC, anavisnia requested changes

2020-12-14 19:34 UTC, anavisnia commented on css/components/plan.css
>      padding-top: 40px;
Per daug paddingo is virsaus.

2020-12-15 10:21 UTC, Vaidmine approved these changes
look good to me... padding as should be...

2020-12-15 14:17 UTC, anavisnia approved these changes

2020-12-15 14:18 UTC, merged