Footer
front-end-by-rimantas/19-grupe-portfolio-personal pull request #73
Opened 2020-12-14 13:43 UTC by Vaidmine

band new footer w social icons and input form

2020-12-14 13:49 UTC, anavisnia commented on css/components/footer.css
> +    background-color: black;
background-color: #04091e;

2020-12-14 13:53 UTC, vaidas33 requested changes

2020-12-14 13:53 UTC, vaidas33 commented on index.html
>          </div>
nereikalingas div uzdarymas

2020-12-14 13:58 UTC, anavisnia requested changes
background-color: #04091e;

2020-12-14 14:01 UTC, Vaidmine commented
background color pakeičiau, div ištryniau

2020-12-14 14:07 UTC, Alekslov reviewed
reiketu atnaujinti is develop

2020-12-14 15:40 UTC, Alekslov approved these changes
nuostabiai

2020-12-15 01:38 UTC, vaidas33 approved these changes

2020-12-15 09:35 UTC, anavisnia approved these changes
lg

2020-12-15 09:35 UTC, merged