Featured projects
front-end-by-rimantas/19-grupe-portfolio-personal pull request #74
Opened 2020-12-14 15:30 UTC by mindep1

2020-12-14 15:50 UTC, Alekslov reviewed
reiketu iscentruoti elementus, kurie randasi div su filters klase

2020-12-14 15:50 UTC, Alekslov commented on index.html
> +                        <h2>ALL</h2>
reiketu pakeisti h2 ir h4 <a > elementais.

2020-12-15 10:16 UTC, Vaidmine requested changes
trūksta elementų (ALL VECTOR RASTER UI/UX PRINTING) centravimo

2020-12-16 10:58 UTC, anavisnia submitted a review, later dismissed
LG

2020-12-16 11:35 UTC, closed without merging